apiVersion: v1
data:
  mapRoles: |
   - groups:
      - system:masters
      rolearn: arn:aws:iam::308154622365:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::308154622365:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1ARCJ8IIGROXE
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-21T20:33:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1071"
  uid: 1fa6fb11-ffa1-45ba-8651-405a15e0af4d
